spring.application.name=CodingShuttles
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:/Users/adityasingh/project/sping_boot/CodingShuttles/db
spring.datasource.username=adityaDb
spring.datasource.password=adi123
spring.jpa.hibernate.ddl-auto=update